config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  scope '/api' do
    scope '/v1' do
      resources :jobs, only: [:index, :show, :create, :update]
    end
  end
  get 'upload' => 'captricity#upload'
  get 'batch/:id' => 'captricity#get_batch'
  post 'batch' => 'captricity#create_batch'
  post '/upload_files' => 'captricity#upload_files'

  get 'dashboard' => 'main#dashboard', as: 'dashboard'
  root to: 'main#index'
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def dashboard
    @user = current_user
    org = @user.organization
    @jobs = org.jobs
    @batches = org.batches
    @templates = Template.visible
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/dashboard.html.erb
<%= render partial: "partials/header"  %>
<div id="backbone"></div>

<script type="text/javascript">
  Formidably.schema = new captricity.APISchema();
  Formidably.schema.fetch({success: function() {
    console.log("Captricity API ready");
    // Bootstrap models from database to avoid AJAX
    Formidably.Jobs = new Formidably.Collections.Jobs;
    Formidably.Batches = new Formidably.Collections.Batches;
    Formidably.Documents = new Formidably.Collections.Documents;

    Formidably.Jobs.reset(<%= @jobs.to_json.html_safe %>)
    Formidably.Batches.reset(<%= @batches.to_json.html_safe %>)
    Formidably.Documents.reset(<%= @templates.to_json.html_safe %>)

    window.router = new Formidably.Router({currentUser: 
      <%= @user.to_json.html_safe %>});
    Backbone.history.start();
  }}).error(function() {
    console.log("You must be logged in to use the API.");
  });
</script>

<%= render partial: "partials/footer" %>

app/views/main/index.html.erb
<%= render partial: "partials/header"  %>

<div class="image-pane main">
  
</div>
<div class="container top-pad big">
  <%= link_to "Go to the dashboard", dashboard_path, :class => "btn btn-lg btn-block" %>
</div>

<%= render partial: "partials/footer" %>